export const styles = {
  container: {
    minHeight: "100vh",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
  },
  formWrapper: {
    maxWidth: "450px",
    width: "100%",
    background: "rgba(255, 255, 255, 0.95)",
    borderRadius: "20px",
    boxShadow: "0 20px 40px rgba(0, 0, 0, 0.1)",
    backdropFilter: "blur(10px)",
    overflow: "hidden",
    position: "relative",
  },
  header: {
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    padding: "40px 30px",
    textAlign: "center",
    color: "white",
  },
  title: {
    fontSize: "28px",
    fontWeight: "700",
    margin: "0 0 10px 0",
    letterSpacing: "0.5px",
  },
  subtitle: {
    fontSize: "16px",
    opacity: "0.9",
    margin: "0",
  },
  form: {
    padding: "40px 30px",
  },
  formGroup: {
    marginBottom: "25px",
    position: "relative",
  },
  label: {
    display: "block",
    fontSize: "14px",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "8px",
    transition: "color 0.3s ease",
  },
  input: {
    width: "100%",
    padding: "15px 20px",
    fontSize: "16px",
    border: "2px solid #e5e7eb",
    borderRadius: "12px",
    background: "#f9fafb",
    transition: "all 0.3s ease",
    outline: "none",
    boxSizing: "border-box",
  },
  inputFocus: {
    borderColor: "#667eea",
    background: "#ffffff",
    boxShadow: "0 0 0 3px rgba(102, 126, 234, 0.1)",
  },
  inputHover: {
    borderColor: "#d1d5db",
  },
  errorContainer: {
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: "10px",
    padding: "15px",
    marginBottom: "20px",
    display: "flex",
    alignItems: "center",
    animation: "shake 0.5s ease-in-out",
  },
  warningContainer: {
    background: "#fffbeb",
    border: "1px solid #fed7aa",
    borderRadius: "10px",
    padding: "15px",
    marginBottom: "20px",
    display: "flex",
    alignItems: "center",
    animation: "shake 0.5s ease-in-out",
  },
  errorDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#ef4444",
    marginRight: "12px",
    animation: "pulse 2s infinite",
  },
  warningDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#f59e0b",
    marginRight: "12px",
    animation: "pulse 2s infinite",
  },
  errorText: {
    color: "#dc2626",
    fontSize: "14px",
    fontWeight: "500",
    margin: "0",
  },
  warningText: {
    color: "#d97706",
    fontSize: "14px",
    fontWeight: "500",
    margin: "0",
  },
  button: {
    width: "100%",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    border: "none",
    borderRadius: "12px",
    padding: "16px 24px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.3s ease",
    position: "relative",
    overflow: "hidden",
  },
  buttonHover: {
    transform: "translateY(-2px)",
    boxShadow: "0 10px 25px rgba(102, 126, 234, 0.4)",
  },
  buttonActive: {
    transform: "translateY(0)",
  },
  footer: {
    textAlign: "center",
    paddingTop: "20px",
    borderTop: "1px solid #f3f4f6",
    marginTop: "20px",
  },
  footerText: {
    color: "#6b7280",
    fontSize: "14px",
    margin: "0",
  },
  footerLink: {
    color: "#667eea",
    textDecoration: "none",
    fontWeight: "600",
    transition: "color 0.3s ease",
  },
  decorativeElement: {
    position: "absolute",
    width: "100px",
    height: "100px",
    borderRadius: "50%",
    background: "rgba(255, 255, 255, 0.1)",
    pointerEvents: "none",
  },
  decorative1: {
    top: "-50px",
    right: "-50px",
  },
  decorative2: {
    bottom: "-30px",
    left: "-30px",
    width: "80px",
    height: "80px",
  },
};
